[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mypkg"
version = "0.1.0"
description = "A simple CLI package"
authors = [{name = "Your Name", email = "you@example.com"}]

[project.scripts]
mypkg = "mypkg.cli:main"
