[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mypkg"
version = "0.1.0"
description = "A simple CLI package"
authors = [{name = "Your Name", email = "you@example.com"}]

[project.scripts]
mypkg = "mypkg.cli:main"
